name: build-and-deploy
on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - run: npm ci
      - run: npm run build -- --output-path docs --base-href https://vitalii-retel.github.io/my-lab/
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - run: rm -rf docs/*
      - uses: actions/download-artifact@v3
        with:
          name: docs
          path: docs
      - name: Commit if there are changes
        run: |
          if [[$(git status -s)]]; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Auto deploy"
            git push
          else
            echo "No changes"
          fi
